project:
  type: website
  output-dir: docs

website:
  title: "Eshta Bhardwaj"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Eshta_AcademicCV.pdf
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true



